{
    'name': 'hfit',
    'version': '1.1',
    'summary': 'hfit',
    'description': 'hfit',
    'author': 'Franco',
    'website': 'https://hfit.com.ec',
    'category': 'Website',
    'depends': ['website_sale','sale','gym_subscription','account','ecx_edi','point_of_sale','hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/partner.xml',
        'views/sale_order.xml',
        'views/subscription.xml',
        'views/templates.xml',
        'views/account_move.xml',
        'wizard/credit_card_file_wizard.xml',
        'views/credit_card_file_so.xml',
        'wizard/credit_wizard.xml',
        'views/server_action.xml',
        'report/authorization_report.xml',
        'views/res_company_view.xml',
        'views/res_users.xml',
        'views/res_branch_views.xml',
        'views/product_template.xml',
        'views/account_journal.xml',
        'views/pause_subscription_wizard.xml',
        'views/pos_payment_method_views.xml',
        'views/virtuagym_log_views.xml',
        #'data/ir_cron_resume_paused_subscriptions.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'hfit/static/src/js/customer_form_member.js',
           'hfit/static/src/js/profile_photo_preview.js',
        ],
        'point_of_sale._assets_pos': [
            'hfit/static/src/js/payment_screen_payroll.js',
        ],
    },
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
}