from . import res_partner
from . import sale_order
from . import account_move
from . import branchs
from . import credit_card_file
from . import res_users
from . import account_journal
from . import credit_card
from . import sale_order_report
from . import pos_payment_method
from . import res_partner_pos
from . import product_template
from . import virtuagym_log